### ISSUE TITLE
fiberassign doesn't produce reproducible results

### ISSUE THREAD

**Issue by sbailey** [desihub/fiberassign#31] opened 2016-03-25 18:05 UTC
Multiple runs of fiberassign on the same machine using the same compilation produce different results, even when not using random numbers (Bob inspected code by grep+eye and says that none of the random number calls are used by the main fiberassign code).  Possible causes are uninitialized variables being used or array overruns clobbering some other piece of memory that is later used.

After fixing, fiberassign should give bitwise identical results when run on multiple machines, at multiple concurrencies, and by multiple people.

**Comment by rainwoodman** [comment] 2016-03-26 03:30
This looks fun. Where do I find the secret files to reproduce this?

**Comment by rncahn** [comment] 2016-03-28 16:55
Yu

can you get the fiberassign code from desihub?  Checkout master.  Then
make.  Let me know
if you have any trouble.

Bob

**Comment by sbailey** [comment] 2016-03-28 17:28
Doesn't he also need to do something with configuring an hpcports
environment and/or setting some environment variable to tell fiberassign
how to compile?

I think he will also need pointers to what features files / input files to
use to actually run the code.

fiberassign should have documentation that makes this trivially clear, but
there have been enough pieces moving around recently that I'm not sure if
the current docs do that or not.

**Comment by rainwoodman** [comment] 2016-03-28 17:45
I am combing through building. The line

```
#include "fitsio.h"
```
is causing some slight issues. It could have been `<fitsio.h>` or better `<cfitsio/fitsio.h>` (for Fedora at least..)

I really would prefer to reproduce the irrepreducibility of fiberassign on my own computer. Is it possible?

**Comment by tskisner** [comment] 2016-03-28 17:50
The <> bracket convention is preferred over quotes, but this does not 
matter in this case.  Putting a header in quotes simply allows the 
compiler to search in the current working directory.  Since fitsio is 
not in the fiberassign source tree, the two forms are identical.

When searching for headers, the compiler looks in default system 
locations (e.g. /usr/include), and (for gcc anyway) it looks in any 
locations specified by the CPATH environment variable.

If you have cfitsio installed somewhere else, then you must specify the 
include path as part of the compilation with 
"-I/path/to/cfitsio/include"

-T

**Comment by rainwoodman** [comment] 2016-03-28 17:58
@rncahn 

The code compiles. Two questions:

- Which features.txt is failing the deterministic test? 
- Which features.txt is sufficiently small that I can run in 8GBs of memory?

**Comment by rncahn** [comment] 2016-03-28 18:06
test/template_fiberassign.txt  uses the small target lists:

Targfile /project/projectdirs/desi/mocks/preliminary/mtl/v2/mtl-lite.fits
SStarsfile
/project/projectdirs/desi/mocks/preliminary/mtl/v2/stdstars-lite.fits
SkyFfile  /project/projectdirs/desi/mocks/preliminary/mtl/v2/sky-lite.fits
Secretfile
/project/projectdirs/desi/mocks/preliminary/mtl/v2/truth-lite.fits

But right now

script/do_short_fa_surveysim

says
srun -N 1 bin/fiberassign_surveysim test/template_fiberassign_lite.txt

which ought to be
srun -N 1 bin/fiberassign_surveysim test/template_fiberassign.txt

**Comment by sbailey** [comment] 2016-03-28 18:32
That doesn't quite work — template_fiberassign.txt as-is is a *template*,
intended to by copied and updated with the specific output directory, etc.
needed by a particular user.  Within the test directory, "python
test_fiberassign.py" will make the copy+updates, compile from scratch, and
run both vanilla fiberassign and fiberassign_surveysim.

This thread highlights the need to have simple, correct, and complete
documentation for how to compile and run this code.

**Comment by rainwoodman** [comment] 2016-03-28 22:08
I am afraid `test_fiberassign.py` has some chdir magics such that even after I grab all of the necessary files to my local machine, relative paths in the template files doesn't work.

**Comment by rncahn** [comment] 2016-03-28 22:42
I always run on nersc.  Kisner will know how to do this on your laptop

**Comment by tskisner** [comment] 2016-03-28 22:53
I have not touched fiberassign code since testing it many months ago.  The code has changed dramatically since then, so I don't think my previous experience applies.

**Comment by rncahn** [comment] 2016-03-28 23:02
I don't think it is a question of code, but rather setting it to run on the
laptop rather than nersc.

**Comment by tskisner** [comment] 2016-03-28 23:14
All I did last time was take an input parameter file that was given to me, and set the moduloGal parameter to some large number so that only a few galaxies where used.  I copied over the input files to my local machine.  And then I ran it in valgrind.  That's it.  If it is compiled on a laptop, a supercomputer, or a phone, it should not matter right?  I thought it was just an OpenMP executable that takes a parameter file.

**Comment by rainwoodman** [comment] 2016-03-29 02:15
Yes. That's pretty much what I did. Follow the instructions and it ran. The
docentatuon is mostly still uptodate.

The current version of test is crashing valgrind in fedora. A fix could be
non trivial but I will file a bug report at least.

I will also file a PR to die when input survey list file is missing. It
initally didn't yield output because I gave it a wrong file name. It shall
at warn or die on ill input.

Yu

**Comment by rncahn** [comment] 2016-03-29 02:34
I do think the reproducibility issue is resolved, though I still need to
show that we get the same result on edison and cori.  At least successive
runs on edison give identical results. It seems only to have been due to a
drand48 in src/modules/kdTree.h

**Comment by forero** [comment] 2018-05-25 19:56
I've just run fiberassign on Edison and Cori for ~10K tiles and ~20M targets form DR5 (using https://github.com/forero/decals_fiberassign_hack) and I get the same results when I compare each tilefile with fitsdiff.

**Comment by sbailey** [comment] 2018-05-25 20:50
Thanks for the final check.  Closing.

**Comment by forero** [comment] 2018-09-12 17:04
@sbailey @rncahn @tskisner 
I am reopening this issue after getting puzzling results from a simple test. I reshuffled the order of the targets in the `mtl.fits` and I get roughly 5% of the fibers assigned to a different target compared with the original `mtl.fits`. The results in these two cases should be the same, right?

**Comment by tskisner** [comment] 2018-09-12 17:20
I am currently testing my refactored / rewritten version of the code doing the "first-pass" assignment.  I am still working on getting those to agree, but when they do I can also do a test where I take my input mtl.fits and shuffle the order.

Both the old and new codes should loop over fibers in order based on the maximum (priority + subpriority) target available to each.  In the case of equality, we should make sure that the fiber order is deterministic (e.g. based on fiber ID order in that case).

I should be able to investigate this question as part of my consistency tests between the old and new code versions.

**Comment by moustakas** [comment] 2018-09-12 17:31
This issue also points to the need for more extensive unit tests for fiberassignment, also vaguely related to #142.

**Comment by tskisner** [comment] 2018-09-12 17:35
Yes.  The new code has unit tests in python (python setup.py test), although currently I'm using a several MB mtl.fits file for the purpose of testing consistency with the old version of the code.  Once the 2 versions agree on that, I'll try to extract a smaller set of files that still have the essential properties (multiple tiles, on average a few targets per fiber, etc), so that we can check that into the test data directory.

**Comment by sbailey** [comment] 2018-09-12 17:48
@forero thanks for checking this case.  We had previously tested that it was reproducible when using the same inputs and options, but I agree that it should also produce reproducible results if the order of the MTL is shuffled but otherwise the contents are identical.

**Comment by rncahn** [comment] 2018-09-12 19:06
good question.  I would have thought so.

**Comment by forero** [comment] 2019-02-01 22:02
@tskisner @sbailey Some good news. The refactor version gives the same results even if the MTL is shuffled.

**Comment by tskisner** [comment] 2019-02-15 14:41
I believe this issue is resolved by the new code.  Targets are now stored in a dictionary (std::map) keyed on the target ID.  Order in the input files makes no difference.  If duplicate TARGETIDs are found when loading catalogs, the code checks that the RA/DEC matches.  If they do not match, an exception is thrown.  If they **do** match then the code assumes we have a target that has multiple types (for example it is a science target and a standard).  In that case it does a bitwise OR of the DESI_TARGET field and chooses the largest of the priority, subpriority, and obs_remaining.

If the behavior above is not the desired one for reading in such "dual" targets, then let's open a new ticket for discussion about how to handle the case of targets with the same TARGETID being specified twice with different properties.  One solution would simply be to avoid this by giving the same physical object 2 target IDs based on its use case.

Closing this now since the specific issue is obsolete, but definitely open a new ticket if needed.

**Closed by tskisner** 2019-02-15 14:41 UTC
Labels: bug
