### ISSUE TITLE
Addition of lower priority targets to input catalog alters assignments at higher priority 

### ISSUE THREAD

**Issue by apcooper** [desihub/fiberassign#37] opened 2016-04-06 14:21 UTC
I've been testing fiberassign with a variety of realistic mock input catalogs containing different target samples combined in different ways  and with different choices of priority. 

I've found that the assignment of fibers to a set of targets of a given priority class changes (those targets being assigned to later plates/passes and in a small number of cases not assigned at all) depending on whether or not lower priority targets are included in the same input MTL. 

The number of targets affected in this way depends on the details of the input catalog. The assignments to lower priority targets that supersede those those to the high priority targets in these cases are technically valid, in the sense that the low priority targets are available to the corresponding tile/fiber, so this is not a bug in that sense, just unintuitive behavior.

I've traced this behavior (with a debugger) to `global.cpp:redistribute_tf()`. From my limited understanding of the code for that function, it seems that it introduces a dependence of the assignment of a target to a particular (tile,fiber) pair on the assignment state of all the other fibers, without any direct connection to the priority of the targets concerned (see the nested if statements [around here](https://github.com/desihub/fiberassign/blob/cf05d13ea07bdd4c131081816e60884c5e45046a/src/global.cpp#L498)).  

Is this the behavior we want? It means that a run of fiberassign is only reproducible with regard to a given priority class `P` if exactly the same MTL file is used, rather than an MTL that is identical only for priorities `p >= P` (as I was expecting naively).

I don't understand `redistribute_tf` well enough to suggest a solution yet. Some additional explanation/comments for this function would help.

**Comment by sbailey** [comment] 2016-04-06 17:26
Thanks for opening this ticket.  I think the behavior we want is as you expected: the reproducibility of higher priority targets should be unaffected by the addition or subtraction of lower priority targets.

A plausible alternative is that we'd be willing to bump a higher priority target to a later epoch if that would enable a lower-priority target to be observed.  i.e. it wouldn't affect the reproducibility of whether the higher priority target is observed, it would just effect when it is observed.  HOWEVER, this should be discussed with Kyle and the survey working group.  "A bird in the hand is worth two in the bush" reasoning might cause us to *not* allow bumping of higher priority targets to later epochs.

Under no circumstances should the addition or subtraction of lower priority targets cause a higher priority target to get dropped (or added for that matter — if it was possible to observe, it should have been observed).

**Comment by rncahn** [comment] 2016-04-06 18:53
The purpose of "redistribute" is to even out the distribution of unassigned
fibers.  If this isn't done, we start with a distribution where all the
unassigned fibers are near the end of the survey.  This is a problem
because we want to use unassigned fibers for the standard stars and sky
fibers.

I believe that the current redistribution code does not result in the loss
of any assigned targets. A target that has high priority might be
reassigned to a point later in the survey so that altogether we reach more
targets but it is never the case that we lose a high priority target in
favor of a lower priority one.

As for reproducibility, that will always require that we have the full
history of the MTL as history.

**Comment by apcooper** [comment] 2016-04-06 20:23
>  it is never the case that we lose a high priority target in favor of a lower priority one.

OK, I thought that would probably be the case, I just couldn't figure out how exactly the code in `redistribute_tf` made sure of it. 

The light-weight test case I've been using to look into this indeed only shows cases of high priority targets being moved to later in the survey, but I'm fairly sure I saw a handful of cases where targets were lost altogether in an earlier test with a much larger MTL. I was using a late-ish version of v3_newio for that, so redistribute might have changed in the meantime. I'll try and repeat that test with the current version.

**Comment by sbailey** [comment] 2016-04-06 20:45
Thanks for redoing your tests with the latest code; please let us know the results.  This should definitely be something that the code actively ensures (i.e. not losing high priority targets should be by design not luck) and we should explicitly test that (trust, but verify).

**Comment by apcooper** [comment] 2017-03-14 12:34
This is just to let you (@sbailey @rncahn @forero @moustakas and anyone else concerned) know that we're now looking into this again in earnest, in response to some ongoing tests by Jianhua He (Durham) of the fiber assignment efficiency for BGS targets in the 2016 data challenge. 

It looks as if the fraction of (high priority) BGS galaxies that are assigned fibres varies across the sky in rough proportion to the density of (lower priority) MWS stars. This was raised in a recent BGS telecon. Jianhua is doing more detailed tests now and will report back in due course.

Does anyone know of any documentation of decisions made by Kyle et al. in relation to [@sbailey's comment above](https://github.com/desihub/fiberassign/issues/37#issuecomment-206476127) about redistributing high priority targets to later epochs?

**Comment by forero** [comment] 2017-03-16 15:37
@apcooper how does that fraction (high/low priority) changes in time? If that fraction is roughly constant, then the problem might be due to this bug #60 (fixed in January, but present in the fiberassign version we used in December).

**Comment by apcooper** [comment] 2017-03-16 16:05
Thanks for pointing to #60, @forero. But what do you mean exactly by 'changes in time'? From one epoch to the next?

I can't figure out what the effect of #60 was, either from the issue or the code. Do you have a layman's explanation?

We're stalled looking into this temporarily because Jianhua is traveling. Your help figuring out how to get going again with [my own runs of the survey simulation](https://github.com/desihub/quicksurvey_example/issues/12) is much appreciated -- that would allow me to do some simplified alternative runs to test this in a different way to Jianhua's forensics of the datachallenge tile map files (and with different versions of FA, if it comes to that).

**Comment by forero** [comment] 2017-03-16 16:09
Right, "changes in time" means "from one epoch to the next."
The effect of #60 was to mistake low priority target as high priority targets and vice versa.
I can help you to prepare simplified runs over ~100 sqdeg, would that be helpful? the whole footprint would be too painful to run.

**Comment by apcooper** [comment] 2017-03-16 16:20
Thanks -- I was hoping to use the mechanism for selecting a small area following the example in the quicksurvey yaml. It looks straightforward but any pointers are welcome (maybe [on the quicksurvey thread](https://github.com/desihub/quicksurvey_example/issues/12)).

Regarding the variation with epochs question: we don't know if it varies in time or not, but we can check. #60 certainly looks like a possible culprit -- is it the case that it only affects epochs after the first?

**Comment by forero** [comment] 2017-03-16 16:37
#60 should affect every epoch.

**Comment by apcooper** [comment] 2017-03-16 16:47
OK, thanks. I'll work on new survey sims on small patches using version in which #60 is fixed. Will report back when we have results.

**Comment by apcooper** [comment] 2017-03-31 11:56
Jianhua has compared the 2016 datachallenge output to a simulation I ran recently at durham using desitarget 0.9.0 and this recent commit of fiberassign: d6a5c2598c47bf438f7d8e25d4d6164cbd205f76. 

I refer to our local run as MWSv3test; the mocks, target cuts, ordering etc. were the same as those in the data challenge. The most significant difference was the tile ordering -- I used simple lists of tiles for each epoch split by pass, rather than the 'obsconditions' approach (see desihub/quicksurvey_example#12). That doesn't make any difference for the purposes of this issue.

The results are summarized in PDFs on the [BGS telecon page](https://desi.lbl.gov/trac/wiki/BrightGalaxyWG/TeleconNotes).

Data Challenge:
https://desi.lbl.gov/trac/attachment/wiki/BrightGalaxyWG/TeleconNotes/DESI_mock.pdf
MWSv3test:
https://desi.lbl.gov/trac/attachment/wiki/BrightGalaxyWG/TeleconNotes/BGSFibre.pdf

Summary: the results from MWSv3test meet expectations that highest-priority BGS targets should have high completeness, should get done in early epochs, and should not have a sky gradient. None of those expectations were met in the data challenge results, implying that #60 had a significant effect (hence the datachallenge outputs are not particularly useful to BGS/MWS).

We've also verified that results for BGS are similar if we remove the MWS stars altogether.

**Comment by sbailey** [comment] 2017-04-03 18:17
Thanks for these comparisons.  We're discussing rerunning the equivalent of the December 2016 data challenge with the fixed version of fiber assign so that there is a reference copy that is useful for MWS and we don't diverge too much.  We just need to find the time to babysit it; due to the memory and runtimes needed it wasn't a completely fire-and-forget automated process.

**Comment by forero** [comment] 2017-10-13 06:00
This was solved in #60.

**Closed by forero** 2017-10-13 06:00 UTC
